### ISSUE TITLE
Include source version information

### ISSUE THREAD

**Issue by matthewrj** [GoogleCloudPlatform/cloud-debug-java#1]
I have this working but the Google Cloud Debug console says it cannot find the source version information. All works well if I point it at local files but it would be great if I can point it at my Cloud Repository.

In the docs it mentions generating source-context.json. The command doesn't seem to exist anymore. Has this been deprecated?

**Comment by b-daniels** [comment]
The command to generate source-context.json was recently changes from "gcloud preview app gen-repo-info-file" to "gcloud beta debug source gen-repo-info-file", and I am embarrassed to say that I omitted the "source" part of the new command when I updated the docs. Both of those commands will work for a while, though.

**Comment by matthewrj** [comment]
Ok great thanks. And where do I put the source-contexts.json file? The docs say to put it in "WEB-INF/classes/". I'm not running a web servlet, I'm just running a jar with a main class. Do I put the source-contexts.json in the classpath? Or do I create the directory and include WEB-INF/classes/source-contexts.json in the jar?

**Comment by alexander-yevsyukov** [comment]
[Docs for setting up Stackdriver under Compute Engine](https://cloud.google.com/debugger/docs/setting-up-on-compute-engine#generate_the_source_context_file) mention `WEB-INF/classes` in the command line argument. So it looks like the Stackdriver should expect it in the same place in WARs and JARs.

**Comment by b-daniels** [comment]
It should actually work anywhere in the class path. I haven't tested that,
though.

**Comment by patflynn** [comment]
@b-daniels I haven't been able to get this to work with my project:
https://github.com/patflynn/kplay

The modules show up in the CDB UI and I can set snapshots, but source context is not successfully detected.  I verified that 
source-context.json
source-contexts.json

are both on the classpath (it's springboot so they're in BOOT-INF/classes.).  I also tried placing them in the jar root and that didn't seem to help.

**Comment by patflynn** [comment]
@b-daniels actually I take that back.  I think that they deployment with the source context files in the jar root path ended up working.

**Comment by patflynn** [comment]
FYI this is actually kinda tricky to do because spring boot does some post packaging magic and moves stuff around.  I ended up editing the jar manually after the build.  

Also I tried placing the context files in the base image of the container and that didn't work.

**Comment by Lovygoogle** [comment]
[MODULE_PACKAGE_DIR]
