### ISSUE TITLE
UnsupportedOperationException on Java 11

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/cloud-debug-java#11]
When using the agent in a Java 11 binary, I gete an `UnsupportedOperationException` when trying to resolve a source location

`Java exception Ljava/lang/UnsupportedOperationException; thrown at ClassPathLookup.resolveSourceLocation: java.lang.UnsupportedOperationException`

Unfortunately there's no stack trace logged.

The README mentions Java 7+ are supported, but I wonder if it fails on Java 10+, which changed permissions for mucking with the class loader.

**Comment by anuraaga** [comment]
Ah I guess it's this line - it needs to be updated to support newer bytecode

https://github.com/GoogleCloudPlatform/cloud-debug-java/blob/master/src/agent/internals/src/main/java/com/google/devtools/cdbg/debuglets/java/ClassResourcesIndexer.java#L87

**Comment by anuraaga** [comment]
Confirmed the issue goes away using the binary in the Github release. I think the binary linked in the README either needs to be updated or the README changed to link to the Github release page instead.

**Comment by hrasadi** [comment]
Fresh binaries is now available through 'https://storage.googleapis.com/cloud-debugger/compute-java/debian-wheezy/cdbg_java_agent_gce.tar.gz'.

Thanks again for letting us know about the problem.
