### ISSUE TITLE
Passing certain agentlib settings causes the agent not to work

### ISSUE THREAD

**Issue by wleese** [GoogleCloudPlatform/cloud-debug-java#22]
I was testing Google Cloud Debugger and had left these jvm parameters in the invocation of my application:

`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005`

These settings are recommended by IntelliJ when doing remote debugging, using the IntelliJ debugger.
Trying to create a snapshot resulted in this unhelpful error in the Google Cloud Debugger UI:
`Internal error at jvm_breakpoint.cc:641 `
.. and these logs in the container:
```
I0406 11:00:14.996963    29 jvm_breakpoints_manager.cc:153] Setting new breakpoint: 5dbf896f4d957-87a1-177f
I0406 11:00:14.997048   151 jvmti_agent_thread.cc:95] Agent thread started: CloudDebugger_transmission_thread
I0406 11:00:15.012601    29 jvm_breakpoint.cc:263] Breakpoint 5dbf896f4d957-87a1-177f initialized to pending state, path: example-cloud-app/src/main/java/com/bol/axlexamplecloud/camping/api/CampingController.java, line number: 31, resolved class signature: Lcom/bol/axlexamplecloud/camping/api/CampingController;, resolved method name: getAllCampings, adjusted line number: 31
E0406 11:00:15.012631    29 jvm_breakpoint.cc:105] GetLineNumberTable failed, error: 99
E0406 11:00:15.012635    29 jvm_breakpoint.cc:631] Resolved source location not found, class signature: Lcom/bol/axlexamplecloud/camping/api/CampingController;, method: getAllCampings, adjusted line: 31
I0406 11:00:15.012676    29 jvm_breakpoints_manager.cc:263] Breakpoint 5dbf896f4d957-87a1-177f removed from active breakpoints list
```

It's unclear to me how the agentlib parameters disrupt the agent. Some way of communicating this back to the user (docs, error message, startup failure), could prove useful.

**Comment by jasonborg** [comment]
This issue is because you can't load two debug agents. There are certain debug [capabilities](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#capability)  that debug agents register for, and the first agent the make the register call claims the capability. In this case the the Snapshot Debugger agent would have loaded second and failed to claim the required capabilities.
