### ISSUE TITLE
Add support for dockerized apps

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/cloud-debug-java#3]
It would be very helpful to have either instructions or just a docker image to use cloud debugger for applications running in a dockerized environment

**Comment by emrekultursay** [comment]
You can add the following to your `Dockerfile` to get the debugger installed at `/opt/cdbg` location when building the image:
  ```
ADD https://storage.googleapis.com/cloud-debugger/appengine-java/current/cdbg_java_agent.tar.gz /opt/cdbg/
  RUN tar Cxfvz /opt/cdbg /opt/cdbg/cdbg_java_agent.tar.gz --no-same-owner \
 && rm /opt/cdbg/cdbg_java_agent.tar.gz
```

And then, use the following options when invoking the `java` command:
```
JAVA_OPTS="${JAVA_OPTS} -agentpath:/opt/cdbg/cdbg_java_agent.so \
  -Dcom.google.cdbg.module=MODULE \
  -Dcom.google.cdbg.version=VERSION"
```

Alternatively, you can use the Google-maintained OpenJDK docker image, which comes with the debugger, which you can find [here](https://github.com/GoogleCloudPlatform/openjdk-runtime). That image already performs the steps I explained above in its [Dockerfile](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/0c1167b9a8c3f7112682faefba63f2dbc99e218b/openjdk8/src/main/docker/Dockerfile).
